# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'MohistPDFReader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MohistPDFReader
  pod 'Kingfisher'
  pod 'SwifterSwift'
  pod 'Anatomy'
  pod 'R.swift'
  pod 'SnapKit'
  pod 'Moya'
  pod 'PromiseKit'
  pod 'QRCodeReader.swift', '~> 9.0.1'
  pod 'EFQRCode'
  pod 'MBProgressHUD'
  # https://github.com/psharanda/Atributika
  pod "Atributika"
  pod 'WechatOpenSDK'
  pod 'SwiftyBeaver' 
  pod 'Cache'
#  pod 'GDPerformanceView-Swift', '~> 1.3.2'
end

